# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "san-lorenzo-backend"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "san-lorenzo-backend"
profile = "uni"
parameter_overrides = "DbSecretName=\"rds!db-f6da8e92-6437-4f4f-abf0-14b8f2f24b0d\" JwtSecretName=\"san-lorenzo/jwt/signing-key\" DbHost=\"dweb.coeo4ygwrtif.us-east-1.rds.amazonaws.com\" DbName=\"sanlorenzo\" AllowedOrigins=\"http://localhost:4200,https://staging.d2275u9fh9sj70.amplifyapp.com\" LogLevel=\"Information\""
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
