using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ServerlessAPI.Authentication;
using ServerlessAPI.Dtos;
using ServerlessAPI.Entities;
using ServerlessAPI.Repositories;

namespace ServerlessAPI.Controllers;

[ApiController]
[Authorize(Roles = nameof(Role.Coordinator))]
[Route("coordinador/reportes")]
[Produces("application/json")]
public sealed class CoordinatorReportsController(
    ILogger<CoordinatorReportsController> logger,
    IUserContext userContext,
    ICoordinatorReportRepository repository) : ControllerBase
{
    [HttpGet]
    [ProducesResponseType<IReadOnlyList<CoordinatorReportSummaryResponse>>(
        StatusCodes.Status200OK)]
    [ProducesResponseType<ProblemDetails>(
        StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    public async Task<ActionResult<
        IReadOnlyList<CoordinatorReportSummaryResponse>>> Get(
        [FromQuery] string? reportType,
        CancellationToken ct)
    {
        var reports = await repository.GetAsync(
            userContext.UserId,
            reportType,
            ct);

        return Ok(reports);
    }

    [HttpGet("{id:int}")]
    [ProducesResponseType<CoordinatorReportResponse>(
        StatusCodes.Status200OK)]
    [ProducesResponseType<ProblemDetails>(
        StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    public async Task<ActionResult<CoordinatorReportResponse>> GetById(
        [FromRoute] int id,
        CancellationToken ct)
    {
        var report = await repository.GetByIdAsync(
            userContext.UserId,
            id,
            ct);

        return report is null
            ? NotFound(new ProblemDetails
            {
                Status = StatusCodes.Status404NotFound,
                Title = "Not found",
                Detail = $"El reporte {id} no existe o no pertenece al coordinador autenticado.",
            })
            : Ok(report);
    }

    [HttpPost("generar")]
    [ProducesResponseType<CoordinatorReportResponse>(
        StatusCodes.Status201Created)]
    [ProducesResponseType<ValidationProblemDetails>(
        StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    [ProducesResponseType<ProblemDetails>(
        StatusCodes.Status404NotFound)]
    public async Task<ActionResult<CoordinatorReportResponse>> Generate(
        [FromBody] GenerateCoordinatorReportRequest request,
        CancellationToken ct)
    {
        var userId = userContext.UserId;

        var report = await repository.GenerateAsync(
            userId,
            request,
            ct);

        logger.LogInformation(
            "Coordinator report {ReportId} of type {ReportType} generated by user {UserId}",
            report.Id,
            report.ReportType,
            userId);

        return StatusCode(
            StatusCodes.Status201Created,
            report);
    }
}
